name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
#    services:
#      mongo:
#        image: mongo:7
#        ports: ["27017:27017"]
#        options: >-
#          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
#          --health-interval=5s --health-timeout=5s --health-retries=30
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pip-tools (pinned)
        run: python -m pip install -U pip setuptools wheel "pip-tools==7.4.1"

      - name: Recompile and verify requirements are up to date
        env:
          CUSTOM_COMPILE_COMMAND: "pip-compile (CI standardized)"
        run: |
          pip-compile --no-header --no-annotate --strip-extras \
            -o requirements.txt requirements.in
          if [ -f requirements-dev.in ]; then
            pip-compile --no-header --no-annotate --strip-extras \
              -o requirements-dev.txt requirements-dev.in
          fi
          git diff --exit-code -- requirements*.txt

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps (dev)
        run: |
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            pip install -r requirements.txt
          fi

      - name: Lint (ruff) & Format check (black)
        run: |
          ruff check .
          black --check .

      - name: Type-check (mypy)
        run: mypy app

      - name: Materialize Firebase credentials
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$RUNNER_TEMP/creds"
          cred_file="$RUNNER_TEMP/creds/firebase.json"
          echo '${{ secrets.FIREBASE_CREDENTIALS }}' > "$cred_file"
          chmod 600 "$cred_file"
          echo "FIREBASE_CRED_PATH=$cred_file" >> "$GITHUB_ENV"

      - name: Run tests (unit first, then integration)
        env:
          FIREBASE_CRED_PATH: ${{ env.FIREBASE_CRED_PATH }}
          MONGO_DSN: ${{ secrets.MONGODB_KEY }}
          FIREBASE_CRED: ${{ secrets.FIREBASE_CRED }}
          FIREBASE_FRONTEND_CRED: ${{ secrets.FIREBASE_FRONTEND_CRED }}
            

        run: |
          pytest -q tests/unit --maxfail=1
          pytest -q tests/integration --maxfail=1
